name: lech
recipe: drupal9
config:
  webroot: web
  drush: false

# Chrome and selenium.
#compose:
#  - scripts/lando/docker-compose-extra.yml

services:
  appserver:
    build_as_root:
      - echo "🍮 Installing drush launcher to /usr/local/bin/drush"
      - wget -q -O /usr/local/bin/drush "https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar" && chmod +x /usr/local/bin/drush
    overrides:
      environment:
        # Drop /app/web/vendor/bin off the front.
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/.composer/vendor/bin
tooling:
 drush:
   path: /usr/local/bin/drush
