name: lecapi
recipe: drupal9
config:
  webroot: web
  # Off by default for performance. Set to `true` and run `lando rebuild` (will not reset database).
  xdebug: false
keys:
  - id_rsa
tooling:
  drush:
    # Override .lando.upstream.yml
    service: appserver
  # @see docs/backend.md.
  sync-prod:
    service: appserver
    description: Syncs prod database and files to local.
    cmd:
      - drush sql:sync @prod @self --yes
      - drush cache:rebuild
      - drush user:login
services:
  solr:
    type: solr:7.7
    portforward: true
    core: drupal
    config:
      dir: .platform/configsets/solr7
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
