name: lecapi
recipe: drupal9
config:
  webroot: web
  xdebug: false
tooling:
  drush:
    # Perhaps temporary fix for drush tooling using the wrong service.
    service: appserver
services:
  solr:
    type: solr:7.7
    portforward: true
    core: drupal
    config:
      dir: .platform/configsets/solr7
