field.storage_settings.entityitems_field:
  type: mapping
  label: Items storage settings
  mapping:
    foo:
      type: string
      label: Foo

field.field_settings.entityitems_field:
  type: mapping
  label: Items field settings
  mapping:
    bar:
      type: string
      label: Bar

field.value.entityitems_field:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.entityitems_widget:
  type: mapping
  label: Items widget widget settings
  mapping:
    foo:
      type: string
      label: Foo

field.formatter.settings.entityitems_formatter:
  type: mapping
  label: Items formatter formatter settings
  mapping:
    foo:
      type: string
      label: Foo
