field.field.*.*.*.third_party.field_instance_options:
  type: mapping
  label: 'Field instance allowed values options'
  mapping:
    instance_allowed_values:
      type: sequence
      label: 'Allowed values list'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'
          label:
            type: label
            label: 'Label'
