version: 2.1
executors:
  default:
    docker:
      - image: drupal:9.0.7-apache
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: default
          MYSQL_ROOT_PASSWORD: lilengine
      - image: selenium/standalone-chrome
commands:
  prepare_environment:
    description: "Prepare tooling, setup path for environment"
    steps:
      - run:
          name: Prepare codebase
          command: |
            apt update && apt install git -y
            echo "export PATH=$PATH:$HOME/project/vendor/bin" >> $BASH_ENV
            composer install -d /root/project
            rm -rf /var/www/html
            ln -s /root/project/web/ /var/www/html
  prepare_drupal:
    description: "Install Drupal instance ready for testing"
    steps:
      - run:
          name: Install Drupal
          command: |
            cd /root/project
            cp .circleci/phpunit.xml phpunit.xml
            cp .circleci/circleci.settings.php web/sites/default/local.settings.php
            composer install
            drush si minimal --db-url=mysql://root:lilengine@127.0.0.1/default --account-pass="admin"
  start_server:
    description: "Start web server ready for functional testing"
    steps:
      - run:
          name: Start server
          command: |
            chown -R www-data:www-data /root/project
            chmod -R 755 /root
            /etc/init.d/apache2 start
jobs:
  coding_standards:
    executor:
      name: default
    steps:
      - checkout
      - prepare_environment
      - run:
          name: Test coding standards
          command: phpcs
  phpunit_tests:
    executor:
      name: default
    steps:
      - checkout
      - prepare_environment
      - prepare_drupal
      - start_server
      - run:
          name: Run PHPUnit tests
          command: phpunit -c ./phpunit.xml

workflows:
  version: 2
  testing:
    jobs:
      - coding_standards
          name: Coding standards
      - phpunit_tests
          name: Tests
          requires:
            - coding_standards
